// GENERATED by scripts/build-video-meta.mjs on 2026-08-28. Do not edit by hand.
//
// Real numbers about real videos, pulled with yt-dlp. Two jobs:
//
// 1. VideoObject structured data. Google asks for uploadDate, duration and a
//    stable thumbnail, and gives "key moments" treatment to a video that
//    declares its chapters. Guessing any of that is how you end up asserting
//    something Google can check and find wrong.
// 2. The credibility line. Someone who arrives from a search result has never
//    heard of Oleg; "48,732 views" is the fastest honest answer to "why should
//    I read this".

export type VideoChapter = { label: string; start: number };

export type VideoMeta = {
  id: string;
  title: string;
  /** View count when the data was last pulled. See VIDEO_STATS_CHECKED. */
  views: number;
  /** Runtime in seconds. */
  seconds: number;
  /** ISO date the video went live on YouTube, NOT the date the page changed. */
  uploadDate: string;
  chapters: VideoChapter[];
};

export const VIDEO_STATS_CHECKED = "2026-08-28";

export const VIDEOS: Record<string, VideoMeta> = {
  "JhtbnZUU_8E": {
    id: "JhtbnZUU_8E",
    title: "My Claude System For Viral Instagram Reels",
    views: 122087,
    seconds: 986,
    uploadDate: "2026-03-10",
    chapters: [
      { label: "Preview of the system", start: 0 },
      { label: "Part 1: System in action", start: 96 },
      { label: "Part 2: How to set it up", start: 364 },
      { label: "Part 3: Other marketing tasks", start: 642 },
    ],
  },
  "QoiFASDh8J8": {
    id: "QoiFASDh8J8",
    title: "How I Use Claude For Cold Outreach (B2B Sales)",
    views: 48764,
    seconds: 619,
    uploadDate: "2026-03-24",
    chapters: [
      { label: "Intro", start: 0 },
      { label: "Cowork doing cold outreach", start: 61 },
      { label: "Cowork finds leads for you", start: 249 },
      { label: "Free setup guide", start: 406 },
    ],
  },
  "AKtT6NLZGoM": {
    id: "AKtT6NLZGoM",
    title: "How I Use Claude Code For Marketing (SMM, Ads, Outreach)",
    views: 32397,
    seconds: 436,
    uploadDate: "2026-03-17",
    chapters: [
      { label: "Showing 5 use cases", start: 0 },
      { label: "Two APIs that we need", start: 242 },
      { label: "How to set it up", start: 306 },
    ],
  },
  "SUZYKyIujQY": {
    id: "SUZYKyIujQY",
    title: "My Claude Code System For Banger Instagram Reels",
    views: 8412,
    seconds: 879,
    uploadDate: "2026-08-04",
    chapters: [
      { label: "Preview of the system", start: 0 },
      { label: "Part 1: Videos the system made for me", start: 76 },
      { label: "Part 2: How to set it up", start: 311 },
      { label: "Part 3: Pricing and pro tips", start: 518 },
    ],
  },
  "QOuH88WW7bQ": {
    id: "QOuH88WW7bQ",
    title: "Claude Code for Content Creation in 10 Minutes",
    views: 23284,
    seconds: 625,
    uploadDate: "2026-03-05",
    chapters: [
      { label: "Generating 10 top quality posts", start: 0 },
      { label: "Part 1: How it works", start: 110 },
      { label: "Part 2: How to set it up", start: 252 },
      { label: "Part 3: Using it", start: 536 },
    ],
  },
  "GK3JFG7x7LA": {
    id: "GK3JFG7x7LA",
    title: "My Claude Code System For Viral Social Media Growth",
    views: 8385,
    seconds: 1052,
    uploadDate: "2026-04-09",
    chapters: [
      { label: "Intro", start: 0 },
      { label: "What this looks like", start: 139 },
      { label: "How to set it up", start: 718 },
      { label: "The secret that made it 5x better", start: 896 },
    ],
  },
  "lw69SOTKRM4": {
    id: "lw69SOTKRM4",
    title: "My Claude Code System For Viral TikTok Videos",
    views: 10790,
    seconds: 774,
    uploadDate: "2026-04-21",
    chapters: [
      { label: "Preview of the system", start: 0 },
      { label: "Part 1: System in action", start: 98 },
      { label: "Part 2: How to set it up", start: 305 },
      { label: "Part 3: Improving it", start: 543 },
    ],
  },
  "Jjz4YxtlwHQ": {
    id: "Jjz4YxtlwHQ",
    title: "How I Use Claude Code For B2B Outreach (35% Reply Rate)",
    views: 20669,
    seconds: 710,
    uploadDate: "2026-04-02",
    chapters: [
      { label: "Intro", start: 0 },
      { label: "How to find leads", start: 132 },
      { label: "How to score leads", start: 374 },
      { label: "Cold outreach messages", start: 554 },
    ],
  },
  "mFYKAsGcnso": {
    id: "mFYKAsGcnso",
    title: "Anthropic Just Revealed How the Top 1% Use AI",
    views: 5916,
    seconds: 646,
    uploadDate: "2026-07-21",
    chapters: [
      { label: "Intro", start: 0 },
      { label: "Levels 0 to 2", start: 49 },
      { label: "Level 3", start: 254 },
      { label: "Level 4", start: 453 },
    ],
  },
  "JQQhT0edXXw": {
    id: "JQQhT0edXXw",
    title: "I Built an X/Twitter Content Machine With Claude Code",
    views: 7374,
    seconds: 917,
    uploadDate: "2026-04-30",
    chapters: [
      { label: "Preview of the system", start: 0 },
      { label: "Part 1: System in action", start: 98 },
      { label: "Part 2: How to set it up", start: 460 },
      { label: "Part 3: Improving it", start: 680 },
    ],
  },
  "sUqLRKyU0PY": {
    id: "sUqLRKyU0PY",
    title: "Claude Just Made Math History (Explained Simply)",
    views: 9801,
    seconds: 535,
    uploadDate: "2026-08-11",
    chapters: [
      { label: "Intro", start: 0 },
      { label: "Part 1: Primes and waves", start: 70 },
      { label: "Part 2: How Claude did it", start: 242 },
      { label: "What it does not mean", start: 415 },
    ],
  },
  "bz1C3dmiOvg": {
    id: "bz1C3dmiOvg",
    title: "Anthropic Engineers Just Fixed Claude Code's Biggest Problem",
    views: 7455,
    seconds: 470,
    uploadDate: "2026-08-09",
    chapters: [
      { label: "Sessions can now talk", start: 0 },
      { label: "Cut your context bill", start: 108 },
      { label: "Where I actually use it", start: 230 },
      { label: "Name and resume sessions", start: 351 },
    ],
  },
};

export function videoMeta(id: string | undefined): VideoMeta | undefined {
  return id ? VIDEOS[id] : undefined;
}

/** ISO 8601 duration, the only format Google accepts on VideoObject.duration. */
export function isoDuration(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `PT${m}M${s}S`;
}

/** "16:26", for the runtime chip next to the player. */
export function clock(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${String(s).padStart(2, "0")}`;
}

/** "122K", for the view-count chip. Full precision reads as false accuracy. */
export function compactViews(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1).replace(/\.0$/, "")}M`;
  if (n >= 1_000) return `${Math.round(n / 1_000)}K`;
  return String(n);
}

/** The canonical watch url, optionally deep linked to a second. */
export function watchUrl(id: string, start?: number): string {
  return `https://www.youtube.com/watch?v=${id}${start ? `&t=${start}s` : ""}`;
}

/**
 * maxresdefault exists for all twelve of these (checked 2026-08-28); it is the
 * only ytimg size that clears Google's thumbnail guidance comfortably.
 */
export function thumbnailUrl(id: string): string {
  return `https://i.ytimg.com/vi/${id}/maxresdefault.jpg`;
}
