import type { Metadata } from "next";
import { Nunito, Comic_Neue } from "next/font/google";
import { FilmedPageOutro } from "@/components/filmed-page-outro";

// The deck's two faces, the same pair /claude-riemann-hypothesis and
// /boris-cherny-ai load and for the same reasons. Nunito carries the slide
// titles — heavy, round and friendly, so a hard idea does not look severe.
// Comic Neue is the hand-drawn label face inside the diagrams; it is what makes
// the Excalidraw-style artwork read as drawn rather than rendered.
const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["600", "800", "900"],
  display: "swap",
});

const comic = Comic_Neue({
  subsets: ["latin"],
  variable: "--font-comic",
  weight: ["700"],
  display: "swap",
});

const TITLE = "11 Things Andrej Karpathy Actually Does With AI";
const DESCRIPTION = "Eleven rules read out of 37 interviews and 3,035 posts by Andrej Karpathy, one to a slide. Why he spends a fifth of his time deliberately lost, why he never asks a model what it thinks, why he asks for HTML instead of text, why he rambles at a microphone for ten minutes, and why he builds his agents a wiki instead of a memory.";
const SHORT = "Eleven rules from Andrej Karpathy, one to a slide, read out of 37 interviews and 3,035 of his posts.";

// SERP note (2026-08-27): `description` is SHORT, not DESCRIPTION. DESCRIPTION runs
// 200 to 320 characters, and Google cuts a description at about 160, so the tail
// (which is where the specific words are) never showed. SHORT was already written
// to be the one-line version. Enforced by tests/e2e/metadata.spec.ts (86).
// THIS FILE IS GENERATED by the vault port script. This edit will be overwritten
// on the next port: make the same change in the script's layout template.
export const metadata: Metadata = {
  title: TITLE,
  description: SHORT,
  keywords: [
    "Andrej Karpathy",
    "How Andrej Karpathy uses AI",
    "Karpathy LLM knowledge base",
    "Karpathy autoresearch",
    "agentic engineering",
    "vibe coding",
    "Claude Code",
    "AI coding agents",
    "How to use LLMs",
    "Anthropic",
  ],
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    type: "article",
    url: "https://oleg.ae/andrej-karpathy-ai",
    publishedTime: "2026-08-12T00:00:00Z",
    modifiedTime: "2026-08-12T00:00:00Z",
    authors: ["Oleg Melnikov"],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: SHORT,
  },
  alternates: {
    canonical: "https://oleg.ae/andrej-karpathy-ai",
  },
};

export default function AndrejKarpathyAiLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // The route owns its own ground, reset and type scale, all of it scoped under
  // .akd-page in page.css. The font variables have to land on the same node.
  //
  // FilmedPageOutro sits OUTSIDE the scoped div, the same mount the other
  // filmed pages use: without it the deck's last link is an external tally and
  // the page dead-ends. No videoId yet, the Karpathy video is unpublished; add
  // videoId + videoTitle here (in the port script's template) when it goes
  // live, then re-port.
  return (
    <>
      <div className={`akd-page ${nunito.variable} ${comic.variable}`}>
        {children}
      </div>
      <FilmedPageOutro />
    </>
  );
}
