// The topic chips on /reels, and the raw tags behind each one.
//
// GENERATED by build_topics.py in the vault, at
// software/viral_reels_database/scripts/build_topics.py.
// Do not hand-edit: regenerate after the library grows, because the reel counts
// below are a measured snapshot and go stale as reels are added.
//
// The reels carry a free-form `tags` text[] written one reel at a time, and it
// cannot be shown as chips. 44,508 distinct strings over 7,802 reels, and most
// of them are either identity ("noel deyzel", "khabane lame", "mrbeast" name the
// creator, not the subject, so a chip made from one filters the library down to
// a single account), format noise true of everything here ("viral video" alone
// is on 415 reels), or the same idea spelled eight ways ("comedy", "comedy skit",
// "comedy video", "comedy short", "comedy sketch", "funny video", "funny skit",
// "relatable comedy"). So the chips are curated topics instead, each backed by
// the real tag strings that belong to it, ORed together by browseReels' existing
// array-overlap filter.
//
// Each topic carries at most 12 tags, and that ceiling is not a style choice:
// browseReels slices `filters.tags` at 12 before building the PostgREST
// `ov.{...}` literal, so a thirteenth tag would be dropped without a word and
// the chip would quietly under-count. The twelve are picked by greedy set cover,
// not by raw popularity, because the most common tags in a topic are also the
// ones that co-occur most; `reels` below is measured against exactly the twelve
// that shipped.

export type Topic = { id: string; label: string; tags: string[]; reels: number };

export const TOPICS: Topic[] = [
  {
    id: "comedy",
    label: "comedy",
    reels: 1674,
    tags: [
      "funny video",
      "comedy skit",
      "comedy",
      "funny reaction",
      "comedy video",
      "funny skit",
      "comedy short",
      "comedy sketch",
      "office humor",
      "tech humor",
      "comedy clip",
      "gym humor",
    ],
  },
  {
    id: "mindset",
    label: "mindset",
    reels: 585,
    tags: [
      "self improvement",
      "motivation",
      "life advice",
      "mental health",
      "inspiration",
      "self care",
      "life lesson",
      "morning routine",
      "productivity",
      "daily routine",
      "health tips",
      "healthy lifestyle",
    ],
  },
  {
    id: "visual-effects",
    label: "visual effects",
    reels: 571,
    tags: [
      "visual effects",
      "video editing",
      "magic trick",
      "illusion",
      "camera trick",
      "fast cuts",
      "optical illusion",
      "photo editing",
      "camera tricks",
      "match cut",
      "video transition",
      "visual trick",
    ],
  },
  {
    id: "travel",
    label: "travel",
    reels: 534,
    tags: [
      "travel vlog",
      "travel",
      "nature",
      "outdoor adventure",
      "travel video",
      "travel tips",
      "luxury travel",
      "summer vibes",
      "mountain view",
      "ocean view",
      "outdoor fun",
      "ocean waves",
    ],
  },
  {
    id: "fitness",
    label: "fitness",
    reels: 473,
    tags: [
      "gym motivation",
      "bodybuilder",
      "fitness motivation",
      "fitness",
      "gym humor",
      "workout motivation",
      "workout",
      "fitness humor",
      "fitness tips",
      "fitness advice",
      "activewear",
      "fitness challenge",
    ],
  },
  {
    id: "relationships",
    label: "relationships",
    reels: 427,
    tags: [
      "relationship advice",
      "relationship humor",
      "couple goals",
      "friends",
      "relationship joke",
      "relationship goals",
      "friendship",
      "funny couple",
      "couple humor",
      "couple comedy",
      "relationship comedy",
      "age gap couple",
    ],
  },
  {
    id: "tech",
    label: "tech",
    reels: 402,
    tags: [
      "tech humor",
      "tech review",
      "tech news",
      "unboxing",
      "chatgpt",
      "future tech",
      "ai tools",
      "web design",
      "software developer",
      "speed test",
      "self driving car",
      "phone addiction",
    ],
  },
  {
    id: "money",
    label: "money",
    reels: 393,
    tags: [
      "luxury lifestyle",
      "career advice",
      "business advice",
      "luxury travel",
      "luxury car",
      "stock market",
      "success story",
      "rich lifestyle",
      "personal finance",
      "money",
      "luxury cars",
      "sales call",
    ],
  },
  {
    id: "ai",
    label: "ai video",
    reels: 376,
    tags: [
      "artificial intelligence",
      "ai video",
      "ai art",
      "chatgpt",
      "ai tools",
      "ai video generator",
      "claude ai",
      "ai voice",
      "higgsfield ai",
      "seedance",
      "ai video editing",
      "funny ai voice",
    ],
  },
  {
    id: "satisfying",
    label: "satisfying",
    reels: 312,
    tags: [
      "deep clean",
      "satisfying video",
      "satisfying cleaning",
      "dirty to clean",
      "asmr",
      "before and after",
      "satisfying",
      "relaxing video",
      "epoxy floor",
      "satisfaction",
      "satisfying craft",
      "relaxation",
    ],
  },
  {
    id: "sport",
    label: "sport",
    reels: 306,
    tags: [
      "crowd reaction",
      "sports car",
      "extreme sports",
      "running",
      "sports",
      "football",
      "sports humor",
      "world cup",
      "sports comedy",
      "race car",
      "sports challenge",
      "crowd cheering",
    ],
  },
  {
    id: "home",
    label: "home & diy",
    reels: 300,
    tags: [
      "interior design",
      "home decor",
      "room makeover",
      "creative process",
      "woodworking",
      "cozy home",
      "cozy vibes",
      "jewelry making",
      "custom jewelry",
      "home video",
      "living room",
      "creative art",
    ],
  },
  {
    id: "food",
    label: "food",
    reels: 272,
    tags: [
      "baking tutorial",
      "food video",
      "food review",
      "baking",
      "easy recipe",
      "street food",
      "meal prep",
      "home cooking",
      "fast food",
      "funny cooking",
      "let him cook",
      "fast recipe",
    ],
  },
  {
    id: "animation",
    label: "animation",
    reels: 236,
    tags: [
      "3d animation",
      "animated comedy",
      "animation",
      "stick figure animation",
      "funny animation",
      "cgi animation",
      "animated short",
      "animated story",
      "cartoon animation",
      "educational animation",
      "digital animation",
      "cgi video",
    ],
  },
  {
    id: "family",
    label: "family",
    reels: 181,
    tags: [
      "parenting humor",
      "mom life",
      "parenting",
      "family fun",
      "family vlog",
      "newborn baby",
      "family humor",
      "dad life",
      "parenting advice",
      "family",
      "funny kids",
      "family travel",
    ],
  },
];

export const TOPIC_IDS: ReadonlySet<string> = new Set(TOPICS.map((t) => t.id));

const BY_ID = new Map(TOPICS.map((t) => [t.id, t]));

/**
 * browseReels' own ceiling on `filters.tags`, restated here so this module can
 * respect it rather than be truncated by it. Keep the two in step.
 */
const BROWSE_TAG_LIMIT = 12;

/**
 * Turn the selected topic id into the flat tag list browseReels wants.
 *
 * Written for a list because the route hands one in, but normalizeTopics caps
 * that list at one entry, so in practice this returns exactly one topic's twelve
 * tags and the chip's printed count is exactly what the wall comes back with.
 *
 * The round-robin below is what keeps it honest if the cap is ever raised. Laid
 * end to end, two topics would be 24 tags and browseReels would keep the first
 * 12, so the second chip would contribute nothing at all and "comedy + food"
 * would return precisely the comedy reels. Interleaved, both are represented.
 * Neither arrangement is correct while the ceiling is 12, which is why the cap
 * is 1; see MAX_SELECTED in build_topics.py for the measured numbers.
 */
export function tagsForTopics(ids: string[]): string[] {
  const lists = ids.map((id) => BY_ID.get(id)?.tags ?? []).filter((t) => t.length);
  const out: string[] = [];
  const seen = new Set<string>();
  const deepest = Math.max(0, ...lists.map((l) => l.length));
  for (let rank = 0; rank < deepest && out.length < BROWSE_TAG_LIMIT; rank += 1) {
    for (const list of lists) {
      if (out.length === BROWSE_TAG_LIMIT) break;
      const tag = list[rank];
      if (!tag || seen.has(tag)) continue;
      seen.add(tag);
      out.push(tag);
    }
  }
  return out;
}

/**
 * Clamp an untrusted list of ids down to the ones that exist.
 *
 * Accepts the comma-joined form the URL carries as well as a real array, since
 * `?topics=comedy,food` is what a shared link looks like.
 *
 * Capped at 1, because every extra id widens the PostgREST array literal the
 * browse query sends, and a request naming forty topics is someone probing the
 * endpoint rather than someone filtering reels.
 */
export function normalizeTopics(raw: unknown): string[] {
  const parts =
    typeof raw === "string"
      ? raw.split(",")
      : Array.isArray(raw)
        ? raw.map((v) => (typeof v === "string" ? v : ""))
        : [];
  const out: string[] = [];
  for (const part of parts) {
    const id = part.trim().toLowerCase();
    if (!TOPIC_IDS.has(id) || out.includes(id)) continue;
    out.push(id);
    if (out.length === 1) break;
  }
  return out;
}
